sudo: required
services:
    - docker

before_install:
    - docker build -t mpeg/udemy-docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true mpeg/udemy-docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "ap-northeast-1"
    app: "hamashita-udemy-docker"
    env: "HamashitaUdemyDocker-env-1"
    bucket_name: "elasticbeanstalk-ap-northeast-1-085107194442"
    bucket_path: "hamashita-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
